//------------------------------------------------------------------------------
//     This code was generated by a tool (hand-maintained, NUCS pattern).
//
//     Debe mantenerse en sync con MainWindow.xaml: cada x:Name necesita su
//     accessor + campo aquí. Los cuerpos viven en MainWindow.xaml.g.hpp
//     (generado por MarkupCompilePass2 en $(IntDir)).
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Shapes.h>)
#include <winrt/Microsoft.UI.Xaml.Shapes.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Media.h>)
#include <winrt/Microsoft.UI.Xaml.Media.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::MuteMic::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::MuteMic::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid RootGrid()
        {
            return _RootGrid;
        }
        void RootGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _RootGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Media::ScaleTransform LevelScale()
        {
            return _LevelScale;
        }
        void LevelScale(::winrt::Microsoft::UI::Xaml::Media::ScaleTransform value)
        {
            _LevelScale = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton ThemeModeToggle()
        {
            return _ThemeModeToggle;
        }
        void ThemeModeToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _ThemeModeToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton GlassToggle()
        {
            return _GlassToggle;
        }
        void GlassToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _GlassToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton FrostToggle()
        {
            return _FrostToggle;
        }
        void FrostToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _FrostToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock StartTrayLabel()
        {
            return _StartTrayLabel;
        }
        void StartTrayLabel(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _StartTrayLabel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton StartTrayToggle()
        {
            return _StartTrayToggle;
        }
        void StartTrayToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _StartTrayToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock FrostLabel()
        {
            return _FrostLabel;
        }
        void FrostLabel(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _FrostLabel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Shapes::Rectangle CueNotchGlyph()
        {
            return _CueNotchGlyph;
        }
        void CueNotchGlyph(::winrt::Microsoft::UI::Xaml::Shapes::Rectangle value)
        {
            _CueNotchGlyph = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton CueOffBtn()
        {
            return _CueOffBtn;
        }
        void CueOffBtn(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _CueOffBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton CueEdgesBtn()
        {
            return _CueEdgesBtn;
        }
        void CueEdgesBtn(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _CueEdgesBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton CueCornersBtn()
        {
            return _CueCornersBtn;
        }
        void CueCornersBtn(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _CueCornersBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton CueNotchBtn()
        {
            return _CueNotchBtn;
        }
        void CueNotchBtn(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _CueNotchBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox CuePosCombo()
        {
            return _CuePosCombo;
        }
        void CuePosCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _CuePosCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock TitleStateBadge()
        {
            return _TitleStateBadge;
        }
        void TitleStateBadge(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _TitleStateBadge = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon SettingsGlyph()
        {
            return _SettingsGlyph;
        }
        void SettingsGlyph(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _SettingsGlyph = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel MainView()
        {
            return _MainView;
        }
        void MainView(::winrt::Microsoft::UI::Xaml::Controls::StackPanel value)
        {
            _MainView = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel SettingsView()
        {
            return _SettingsView;
        }
        void SettingsView(::winrt::Microsoft::UI::Xaml::Controls::StackPanel value)
        {
            _SettingsView = value;
        }

        ::winrt::Microsoft::UI::Xaml::Shapes::Ellipse StateDot()
        {
            return _StateDot;
        }
        void StateDot(::winrt::Microsoft::UI::Xaml::Shapes::Ellipse value)
        {
            _StateDot = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock StateText()
        {
            return _StateText;
        }
        void StateText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _StateText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock DeviceText()
        {
            return _DeviceText;
        }
        void DeviceText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _DeviceText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border LevelTrack()
        {
            return _LevelTrack;
        }
        void LevelTrack(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _LevelTrack = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border LevelFill()
        {
            return _LevelFill;
        }
        void LevelFill(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _LevelFill = value;
        }


        ::winrt::Microsoft::UI::Xaml::Controls::Button MuteBtn()
        {
            return _MuteBtn;
        }
        void MuteBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _MuteBtn = value;
        }











        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel ShortcutList()
        {
            return _ShortcutList;
        }
        void ShortcutList(::winrt::Microsoft::UI::Xaml::Controls::StackPanel value)
        {
            _ShortcutList = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button AddShortcutBtn()
        {
            return _AddShortcutBtn;
        }
        void AddShortcutBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _AddShortcutBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox DeviceCombo()
        {
            return _DeviceCombo;
        }
        void DeviceCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _DeviceCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton AutostartToggle()
        {
            return _AutostartToggle;
        }
        void AutostartToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _AutostartToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton SoundToggle()
        {
            return _SoundToggle;
        }
        void SoundToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _SoundToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton TipDeviceToggle()
        {
            return _TipDeviceToggle;
        }
        void TipDeviceToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _TipDeviceToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton TipShortcutToggle()
        {
            return _TipShortcutToggle;
        }
        void TipShortcutToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _TipShortcutToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton PauseToggle()
        {
            return _PauseToggle;
        }
        void PauseToggle(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _PauseToggle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox MuteSoundCombo()
        {
            return _MuteSoundCombo;
        }
        void MuteSoundCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _MuteSoundCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox UnmuteSoundCombo()
        {
            return _UnmuteSoundCombo;
        }
        void UnmuteSoundCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _UnmuteSoundCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider VolumeSlider()
        {
            return _VolumeSlider;
        }
        void VolumeSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _VolumeSlider = value;
        }

    protected:
        bool _contentLoaded{false};

    private:
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _RootGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Media::ScaleTransform _LevelScale{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _ThemeModeToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _GlassToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _FrostToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _StartTrayLabel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _StartTrayToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _FrostLabel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Shapes::Rectangle _CueNotchGlyph{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _CueOffBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _CueEdgesBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _CueCornersBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _CueNotchBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _CuePosCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _TitleStateBadge{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _SettingsGlyph{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel _MainView{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel _SettingsView{nullptr};
        ::winrt::Microsoft::UI::Xaml::Shapes::Ellipse _StateDot{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _StateText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _DeviceText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _LevelTrack{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _LevelFill{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _MuteBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel _ShortcutList{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _AddShortcutBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _DeviceCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _AutostartToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _SoundToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _TipDeviceToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _TipShortcutToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _PauseToggle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _MuteSoundCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _UnmuteSoundCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _VolumeSlider{nullptr};
    };
}
