// This file is generated by the build to support Xaml apps
#include "pch.h"
#include "XamlMetaDataProvider.h"
#if __has_include("XamlMetaDataProvider.g.cpp")
#include "XamlMetaDataProvider.g.cpp"
#endif
